import { Quicksand, Pacifico } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const quicksand = Quicksand({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

const pacifico = Pacifico({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/circle.svg", // main favicon
    apple: "/circle.svg", // optional
  },
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={quicksand.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
